/** © BY CRYSNOVA 2026 do not edit this file all rights reserved 
 * ╔══════════════════════════════════════════════════╗
 * ║         𝗖𝗢𝗗𝗘𝗫 𝐀𝐈 V2.0 - 𝓹𝓻𝓸𝓯𝓮𝓼𝓼𝓲𝓸𝓷𝓪𝓵         ║
 * ║   Connection: 𝗖𝗢𝗗𝗘𝗫 V1.0 (Pairing Code)      ║
 * ║   FIXED: Commands Working + Real Channel Fwd    ║
 * ╚══════════════════════════════════════════════════╝
 */

console.clear();

// ── Core ───────────────────────────────────────────
const express  = require('express');
const http     = require('http');
const socketIo = require('socket.io');
const path     = require('path');
const pino     = require('pino');
const readline = require('readline');
const fs       = require('fs');
const chalk    = require('chalk');
const { Boom } = require('@hapi/boom');

// ── Baileys (dynamic import) ───────────────────────
let makeWASocket, Browsers, useMultiFileAuthState,
    DisconnectReason, fetchLatestBaileysVersion,
    jidDecode, downloadContentFromMessage,
    jidNormalizedUser, makeInMemoryStore;

const loadBaileys = async () => {
    const baileys = await import('@whiskeysockets/baileys');
    makeWASocket              = baileys.default;
    Browsers                  = baileys.Browsers;
    useMultiFileAuthState     = baileys.useMultiFileAuthState;
    DisconnectReason          = baileys.DisconnectReason;
    fetchLatestBaileysVersion = baileys.fetchLatestBaileysVersion;
    jidDecode                 = baileys.jidDecode;
    downloadContentFromMessage= baileys.downloadContentFromMessage;
    jidNormalizedUser         = baileys.jidNormalizedUser;
    makeInMemoryStore         = baileys.makeInMemoryStore;
};

// ── CRYSNOVA Modules ───────────────────────────────
const config       = () => require('./settings/config');
const { smsg }     = require('./library/serialize');
const { getBuffer }= require('./library/function');
const FileType     = require('file-type');

// ── Kord-Style Modules ─────────────────────────────
const { loadCommands }   = require('./src/Plugin/crysLoadCmd');
const { handleMessage }  = require('./src/Plugin/crysMsg');
const { crysStatistic }  = require('./src/Plugin/crysStatistic');

// ── Express + Socket.IO ────────────────────────────
const app    = express();
const port   = process.env.PORT || 3000;
const server = http.createServer(app);
const io     = socketIo(server);

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'Public')));

app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'Public/index.html')));

// ── Global Stats ───────────────────────────────────
global.crysStats = {
    messages: 0,
    commands: 0,
    startTime: Date.now(),
    uptime: 0
};

// ── Global AFK Map ─────────────────────────────────
if (!global.afk) global.afk = new Map();

// ── Global Online Users ────────────────────────────
global.onlineUsers = global.onlineUsers || new Set();

// ── Ignored Errors ─────────────────────────────────
const ignoredErrors = [
    'Socket connection timeout', 'EKEYTYPE', 'item-not-found',
    'rate-overlimit', 'Connection Closed', 'Timed Out', 'Value not found',
    'Bad MAC', 'decrypt error', 'Socket closed', 'Session closed',
    'Connection terminated', 'read ECONNRESET', 'write ECONNRESET',
    'ECONNREFUSED', 'connect ETIMEDOUT', 'network timeout'
];

// ── Readline helper ────────────────────────────────
const question = (text) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    return new Promise(resolve => {
        rl.question(chalk.yellow(text), answer => { resolve(answer); rl.close(); });
    });
};

// ── Banner ─────────────────────────────────────────
const showBanner = () => {
    console.log(chalk.cyan(`
╔═══════════════════════════════════════════╗
║   𝗖𝗢𝗗𝗘𝗫 𝐀𝐈  -   𝓹𝓻𝓸𝓯𝓮𝓼𝓼𝓲𝓸𝓷𝓪𝓵        ║
║   CONNECTION : 𝗖𝗢𝗗𝗘𝗫 𝐎𝐅𝐅𝐈𝐂𝐈𝐀𝐋      ║
║   MODEL      : 𝗖𝗢𝗗𝗘𝗫         ║
║ ✪ ALL COMMANDS WORKING + REAL CHANNEL FWD ║
╚═══════════════════════════════════════════╝`));
};

// ═══════════════════════════════════════════════════
// CREATOR COMMAND SYSTEM - MULTI PREFIX SUPPORT
// ═══════════════════════════════════════════════════

// Store all bot instances for creator command
global.botInstances = global.botInstances || new Map();

// Creator command handler
const handleCreatorCommand = async (sock, m, text) => {
    // Check if message starts with creator trigger
    const creatorTriggers = ['✦', '✪', '⚉', '★', '✯'];
    const firstChar = text.charAt(0);
    
    if (!creatorTriggers.includes(firstChar)) return false;
    
    const commandBody = text.slice(1).trim().toLowerCase();
    if (!commandBody) return false;
    
    // Get all connected bots
    const bots = Array.from(global.botInstances.values());
    
    if (bots.length === 0) {
        await sock.sendMessage(m.chat, { 
            text: '✘ _No bot instances available_' 
        }, { quoted: m });
        return true;
    }
    
    // Execute on all bots with their respective prefixes
    const results = [];
    
    for (const botSock of bots) {
        try {
            const botConfig = config();
            const botPrefix = botConfig.prefix || '.';
            const fullCommand = botPrefix + commandBody;
            
            // Create fake message for this bot
            const fakeM = {
                ...m,
                text: fullCommand,
                body: fullCommand,
                msg: fullCommand
            };
            
            // Process command through this bot's handler
            await handleMessage(botSock, fakeM, botSock.store);
            
            results.push({
                bot: botSock.user?.id?.split(':')[0] || 'Unknown',
                prefix: botPrefix,
                executed: true
            });
        } catch (err) {
            results.push({
                bot: botSock.user?.id?.split(':')[0] || 'Unknown',
                error: err.message
            });
        }
    }
    
    // Send confirmation
    let confirmMsg = `╭─❍ *CREATOR COMMAND EXECUTED* 𓉤\n`;
    confirmMsg += `│ Command: ${commandBody}\n`;
    confirmMsg += `│ Bots: ${results.length}\n`;
    confirmMsg += `╰─\n\n`;
    
    results.forEach((res, i) => {
        if (res.executed) {
            confirmMsg += `✓ Bot ${i + 1}: ${res.prefix}${commandBody}\n`;
        } else {
            confirmMsg += `✗ Bot ${i + 1}: Failed\n`;
        }
    });
    
    await sock.sendMessage(m.chat, { text: confirmMsg }, { quoted: m });
    return true;
};

// ═══════════════════════════════════════════════════
// PRESENCE HANDLER - FIXED POSITION
// ═══════════════════════════════════════════════════

async function presenceHandler(sock, update) {
    if (!update.id) return;
    
    const jid = update.id;
    
    if (update.presences && update.presences[jid]) {
        const presence = update.presences[jid].lastKnownPresence;
        
        if (presence === "available" || presence === "composing" || presence === "recording") {
            global.onlineUsers.add(jid);
        } else if (presence === "unavailable" || presence === "paused") {
            global.onlineUsers.delete(jid);
        }
    }
}

module.exports.presenceHandler = presenceHandler;

// ═══════════════════════════════════════════════════
// MAIN CONNECTION
// ═══════════════════════════════════════════════════

const clientstart = async () => {
    await loadBaileys();
    showBanner();

    const browserOptions = [
        Browsers.macOS('Safari'),
        Browsers.macOS('Chrome'),
        Browsers.windows('Firefox'),
        Browsers.ubuntu('Chrome')
    ];

    const randomBrowser = browserOptions[Math.floor(Math.random() * browserOptions.length)];

   
    
    const customStore = {
        messages: new Map(),
        contacts: new Map(),
        groupMetadata: new Map(),
        presences: {},
        loadMessage: async (jid, id) => customStore.messages.get(`${jid}:${id}`) || null,
        bind: (ev) => {
            ev.on('messages.upsert', ({ messages }) => {
                for (const msg of messages) {
                    if (msg.key?.remoteJid && msg.key?.id) {
                        customStore.messages.set(`${msg.key.remoteJid}:${msg.key.id}`, msg);
                    }
                }
            });
            
            // Bind presence updates to store
            ev.on('presence.update', (update) => {
                if (update.id) {
                    customStore.presences[update.id] = update;
                    presenceHandler(sock, update);
                }
            });
        }
    };

    const { state, saveCreds } = await useMultiFileAuthState(`./${config().session}`);
    const { version } = await fetchLatestBaileysVersion();

    const sock = makeWASocket({
        logger: pino({ level: 'silent' }),
        printQRInTerminal: !config().status.terminal,
        auth: state,
        version,
        browser: randomBrowser,
        getMessage: async (key) => {
            return customStore.loadMessage(key.remoteJid, key.id);
        }
    });

    // Pairing Code
    if (config().status.terminal && !sock.authState.creds.registered) {
        const phoneNumber = await question('secured by 𝓬𝓸𝓭𝓮𝔁 𝓸𝓯𝓯𝓲𝓬𝓲𝓪𝓵 enter your WhatsApp number, starting with 234:\nnumber WhatsApp: ');
        const code = await sock.requestPairingCode(phoneNumber);
        console.log(chalk.green(`your pairing code: ` + chalk.bold.green(code)));
    }

    customStore.bind(sock.ev);
    
    // Attach store to sock for global access
    sock.store = customStore;

    // Register this bot instance for creator commands
    const botId = sock.user?.id?.split(':')[0] || Date.now().toString();
    global.botInstances.set(botId, sock);

    // Sock helpers
    sock.decodeJid = (jid) => {
        if (!jid) return jid;
        if (/:\d+@/gi.test(jid)) {
            const decode = jidDecode(jid) || {};
            return decode.user && decode.server ? `${decode.user}@${decode.server}` : jid;
        }
        return jid;
    };

    sock.public = config().status.public;

    sock.downloadMediaMessage = async (message) => {
        let mime = (message.msg || message).mimetype || '';
        let messageType = message.mtype ? message.mtype.replace(/Message/gi, '') : mime.split('/')[0];
        const stream = await downloadContentFromMessage(message, messageType);
        let buffer = Buffer.from([]);
        for await (const chunk of stream) buffer = Buffer.concat([buffer, chunk]);
        return buffer;
    };

    sock.sendText = async (jid, text, quoted = '', options) =>
        sock.sendMessage(jid, { text, ...options }, { quoted });

    sock.ev.on('creds.update', saveCreds);

    // Connection Update
    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update;

        if (connection === 'connecting') console.log(chalk.yellow('🔄 Connecting...'));

        if (connection === 'open') {
            console.log(chalk.green('✅ Connected!'));
            console.log(chalk.cyan(`📱 Number: ${sock.user?.id?.split(':')[0]}`));
            console.log(chalk.cyan(`🌐 Dashboard: http://localhost:${port}\n`));
            
            io.emit('bot-status', { 
                status: 'connected', 
                number: sock.user?.id?.split(':')[0], 
                name: sock.user?.name 
            });

            // 🔥 REAL CHANNEL FORWARD MESSAGE (with View Channel button)
            const botJid = sock.user.id.split(':')[0] + '@s.whatsapp.net';
            
            try {
                // Fetch thumbnail from config
                const cfg = config();
                const thumbUrl = cfg.thumbnail || cfg.thumbUrl || 'https://files.catbox.moe/z2rqc1.jpg';
                
                await sock.sendMessage(botJid, {
                    text: `亗 *${cfg.settings?.title || '𝗖𝗢𝗗𝗘𝗫✦𝐀𝐈'}* is Online!\n\n` +
                        `> ⚉ User: ${sock.user.name || 'Unknown'}\n` +
                        `> 乂 Prefix: [ ${cfg.prefix || '.'} ]\n` +
                        `> ☬ Mode: ${cfg.status?.public ? 'Public' : 'Private'}\n` +
                        `> ✪ Version: 2.0.0\n` +
                        `> 𓉤 Owner: 𝗖𝗢𝗗𝗘𝗫\n\n` +
                        `✓ Bot connected successfully`,
                    contextInfo: {
                        isForwarded: true,
                        forwardedNewsletterMessageInfo: {
                            newsletterJid: '0029Vb6sMEy96H4VI2w3I50f@newsletter',
                            newsletterName: '𝓬𝓸𝓭𝓮𝔁 𝓸𝓯𝓯𝓲𝓬𝓲𝓪𝓵',
                            serverMessageId: 1
                        },
                        externalAdReply: {
                            title: cfg.settings?.title || 'CRYSNOVA',
                            body: '𝗖𝗢𝗗𝗘𝗫✦ 𝐟𝐨𝐥𝐥𝐨𝐰 𝐜𝐡𝐚𝐧𝐧𝐞𝐥',
                            thumbnailUrl: thumbUrl,
                            sourceUrl: 'https://whatsapp.com/channel/0029Vb6sMEy96H4VI2w3I50F',
                            mediaType: 1,
                            renderLargerThumbnail: true,
                            showAdAttribution: true
                        }
                    }
                });
            } catch (sendErr) {
                console.log(chalk.yellow('[Connected msg failed]'), sendErr.message);
            }
        }

        if (connection === 'close') {
            const statusCode = lastDisconnect?.error?.output?.statusCode;
            
            console.log(chalk.red('❌ Connection closed:'), statusCode);
            
            // Remove from bot instances
            global.botInstances.delete(botId);

            if (statusCode === DisconnectReason.loggedOut) {
                console.log(chalk.red('🚫 Logged out. Delete session folder and restart.'));
                process.exit(1);
            } else {
                console.log(chalk.yellow('🔄 Reconnecting in 3 seconds...'));
                setTimeout(clientstart, 3000);
            }
        }

        try {
            const { konek } = require('./library/connection/connection');
            konek({ sock, update, clientstart, DisconnectReason, Boom });
        } catch {}
    });

    // ═══════════════════════════════════════════════════
    // MESSAGE HANDLER
    // ═══════════════════════════════════════════════════

    sock.ev.on('messages.upsert', async (chatUpdate) => {
        try {
            const mek = chatUpdate.messages[0];
            if (!mek || !mek.message) return;

            // Handle ephemeral
            if (mek.message.ephemeralMessage) {
                mek.message = mek.message.ephemeralMessage.message;
            }

            const m = await smsg(sock, mek, customStore);
            if (!m) return;

            // Stats
            global.crysStats.messages++;
            
            io.emit('new-message', {
                from: m.sender,
                chat: m.chat,
                text: m.text || '[Media]',
                isGroup: m.isGroup,
                time: Date.now()
            });

            // ═══════════════════════════════════════════════════
            // 🔥 CREATOR COMMAND CHECK (BEFORE NORMAL COMMANDS)
            // ═══════════════════════════════════════════════════
            
            if (m.text && !m.key.fromMe) {
                const isCreatorCmd = await handleCreatorCommand(sock, m, m.text);
                if (isCreatorCmd) return; // Stop processing if creator command handled
            }

            // ═══════════════════════════════════════════════════
            // 🔥 INVISIBLE TAG TRIGGER (‎‎@everyone)
            // ═══════════════════════════════════════════════════
            
            if (m.text && m.text.startsWith('\u200E\u200E') && m.isGroup) {
                try {
                    const metadata = await sock.groupMetadata(m.chat);
                    const participants = metadata.participants.map(p => p.id);
                    if (participants.length) {
                        const cleanText = m.text.slice(2);
                        await sock.sendMessage(m.chat, {
                            text: cleanText || '\u200E',
                            mentions: participants
                        }, { quoted: m });
                    }
                } catch {}
                return; // Stop processing
            }

            // ═══════════════════════════════════════════════════
            // 🔥 COMMAND ENGINE (MOST IMPORTANT - PROCESS FIRST!)
            // ═══════════════════════════════════════════════════
            
            await handleMessage(sock, m, customStore);

            // ═══════════════════════════════════════════════════
            // 🔥 AFK SYSTEM (AFTER COMMANDS!)
            // ═══════════════════════════════════════════════════
            
            // Skip bot's own messages for AFK
            if (!m.key.fromMe) {
                const afkMap = global.afk;
                const botJid = sock.user.id.split(':')[0] + '@s.whatsapp.net';
                const senderJid = m.key.participant || m.key.remoteJid;
                const mentioned = m.message?.extendedTextMessage?.contextInfo?.mentionedJid || [];

                // 1. Check if someone messages bot while bot is AFK
                if (afkMap.has(botJid)) {
                    const afkData = afkMap.get(botJid);
                    const timeAgo = Math.floor((Date.now() - afkData.time) / 1000 / 60);
                    
                    let botAfkReply = `╭─❍ *AFK NOTICE* 𓉤\n`;
                    botAfkReply += `│ I'm currently *OFFLINE*\n`;
                    botAfkReply += `│ Reason: ${afkData.reason}\n`;
                    botAfkReply += `│ Since: ${timeAgo} minute${timeAgo !== 1 ? 's' : ''} ago\n`;
                    botAfkReply += `╰─ 𓄄 _Will reply when back_`;
                    
                    await sock.sendMessage(m.key.remoteJid, { text: botAfkReply }, { quoted: m });
                }

                // 2. Check if mentioned user is AFK
                const isMentionedAfk = mentioned.some(jid => afkMap.has(jid));
                if (isMentionedAfk) {
                    const targetJid = mentioned.find(jid => afkMap.has(jid));
                    const afkData = afkMap.get(targetJid);
                    const timeAgo = Math.floor((Date.now() - afkData.time) / 1000 / 60);
                    
                    let afkAlert = `╭─❍ *AFK ALERT* 𓉤\n`;
                    afkAlert += `│ @${targetJid.split('@')[0]} is currently **OFFLINE**\n`;
                    afkAlert += `│ Reason: ${afkData.reason}\n`;
                    afkAlert += `│ Been AFK for: ${timeAgo} minute${timeAgo !== 1 ? 's' : ''}\n`;
                    afkAlert += `╰─ 𓄄 _Message will be seen when back_`;
                    
                    await sock.sendMessage(m.key.remoteJid, { 
                        text: afkAlert,
                        mentions: [targetJid]
                    }, { quoted: m });
                }

                // 3. Auto-remove AFK when user sends message
                if (afkMap.has(senderJid)) {
                    const afkData = afkMap.get(senderJid);
                    const timeAgo = Math.floor((Date.now() - afkData.time) / 1000 / 60);
                    afkMap.delete(senderJid);
                    
                    let backMsg = `╭─❍ *BACK ONLINE* 𓉤\n`;
                    backMsg += `│ ${m.pushName || senderJid.split('@')[0]} is back!\n`;
                    backMsg += `│ Was AFK for: ${timeAgo} minute${timeAgo !== 1 ? 's' : ''}\n`;
                    backMsg += `╰────────────────`;
                    
                    await sock.sendMessage(m.key.remoteJid, { 
                        text: backMsg,
                        mentions: [senderJid]
                    }, { quoted: m });
                }
            }

            // ═══════════════════════════════════════════════════
            // 🔥 ANTI-LINK PLUGIN
            // ═══════════════════════════════════════════════════
            
            try {
                const anti = require('./src/Plugin/antilink.js');
                if (anti?.handleAntiLink) {
                    await anti.handleAntiLink(sock, m);
                }
            } catch {}

            // ═══════════════════════════════════════════════════
            // 🔥 MENTION REACTION
            // ═══════════════════════════════════════════════════
            
            try {
                const mentionReact = require('./src/Commands/Owner/mention-react.js');
                if (mentionReact?.handleMentionReaction) {
                    await mentionReact.handleMentionReaction(sock, m);
                }
            } catch {}

            // ═══════════════════════════════════════════════════
            // 🔥 AI AUTO-REPLY (CRYSNOVA AI)
            // ═══════════════════════════════════════════════════
            
            if (m.text && !m.key.fromMe && !m.text.startsWith(config().prefix)) {
                try {
                    let crysAI = null;
                    try {
                        crysAI = require('./src/Commands/AI/codex.js');
                    } catch (e) {
                        // AI plugin not found - skip
                    }
                    
                    if (crysAI?.onMessage) {
                        await crysAI.onMessage(sock, m);
                    }
                } catch (aiErr) {
                    console.error('[AI AUTO]', aiErr.message);
                }
            }

        } catch (err) {
            if (!ignoredErrors.some(e => err.message.includes(e))) {
                console.log(chalk.red('[MSG ERROR]'), err.message);
            }
        }
    });

    // ═══════════════════════════════════════════════════
    // GROUP EVENTS (Welcome/Goodbye)
    // ═══════════════════════════════════════════════════

    sock.ev.on('group-participants.update', async (data) => {

        try {

            const dbPath = './database/groupEvents.json';

            if (!fs.existsSync(dbPath)) return;

            const db = JSON.parse(fs.readFileSync(dbPath));

            if (!db[data.id]?.enabled) return;

            const meta = await sock.groupMetadata(data.id);

            const count = meta.participants.length;

            const groupName = meta.subject;

            if (data.action === 'add') {

                for (const user of data.participants) {

                    const userId = typeof user === 'string' ? user : user.id;

                    const welcomeText = db[data.id].welcome || 'Welcome to the group!';

                    let ppUrl;

                    try { ppUrl = await sock.profilePictureUrl(userId, 'image'); }

                    catch { ppUrl = 'https://i.imgur.com/BoN9kdC.png'; }

                    await sock.sendMessage(data.id, {

                        image: { url: ppUrl },

                        caption: `┏━━━━〔 ✦ 𝗖𝗢𝗗𝗘𝗫 𝐀𝐈 〕━━━━━\n` +

                            `❏┃ Hello @${userId.split('@')[0]}!\n` +

                            `❏┃ Welcome to *${groupName}*!\n` +

                            `❏┃ Members: ${count}\n` +

                            `❏┃ ${welcomeText}\n` +

                            `━━━━━━━━━━━━━━━━━━━━━`,

                        mentions: [userId]

                    });

                }

            }

            if (data.action === 'remove') {

                for (const user of data.participants) {

                    const userId = typeof user === 'string' ? user : user.id;

                    const goodbyeText = db[data.id].goodbye || 'Goodbye!';

                    await sock.sendMessage(data.id, {

                        text: `👋 @${userId.split('@')[0]} left *${groupName}*\n❏┃ ${goodbyeText}\n❏┃ Members: ${count}`,

                        mentions: [userId]
                 
                    });

                }

            }

        } catch (err) {

            console.log('Group Events Error:', err.message);

        }

    });

    // ═══════════════════════════════════════════════════
    // CONTACTS UPDATE
    // ═══════════════════════════════════════════════════

    sock.ev.on('contacts.update', (update) => {
        for (const contact of update) {
            customStore.contacts.set(contact.id, {
                id: contact.id, 
                name: contact.notify || contact.name || null
            });
        }
    });

    return sock;
};

// ── Socket.IO ──────────────────────────────────────
io.on('connection', (socket) => {
    console.log(chalk.cyan('👤 Dashboard connected'));
    socket.emit('stats', global.crysStats);
    socket.on('disconnect', () => console.log(chalk.cyan('👤 Dashboard disconnected')));
});

// ── Error Handling ─────────────────────────────────
process.on('unhandledRejection', reason => {
    if (ignoredErrors.some(e => String(reason).includes(e))) return;
    console.log('Unhandled Rejection:', reason);
});

const origErr = console.error;
console.error = function (msg, ...args) {
    if (typeof msg === 'string' && ignoredErrors.some(e => msg.includes(e))) return;
    origErr.apply(console, [msg, ...args]);
};

// ── Start ──────────────────────────────────────────
(async () => {
    try {
        if (!fs.existsSync('./database')) {
            fs.mkdirSync('./database', { recursive: true });
        }
        if (!fs.existsSync('./database/groupEvents.json')) {
            fs.writeFileSync('./database/groupEvents.json', '{}');
        }
        
        loadCommands();

        server.listen(port, () => {
            console.log(chalk.green(`✅ Dashboard: http://localhost:${port}`));
        });

        crysStatistic(app, io);
        await clientstart();

    } catch (err) {
        console.error(chalk.red('Startup error:'), err);
        process.exit(1);
    }
})();

// ── File Watcher ───────────────────────────────────
let file = require.resolve(__filename);
require('fs').watchFile(file, () => {
    delete require.cache[file];
    require(file);
});
